export const categoryIcons = {
    "Strona główna": "/home.svg",
    "Dodaj pogrzeb": "/plus-circle.svg",
    "Dodaj zlecenie": "/plus-circle.svg",
    "Zleć przewóz": "/briefcase.svg",
    "Historia ceremonii": "/book-open.svg",
    "Historia zleceń": "/book-open.svg",
    "Dodaj pracownika": "/user-plus.svg",
    "Mój zespół": "/users.svg",
    Pracownicy: "/user-settings.svg",
    Zespoły: "/users.svg",
    Statystyki: "/bar-chart.svg",
    Wyszukiwarka: "/magnifying-glass.svg",
    Wypłaty: "/briefcase.svg",
    Rozliczenie: "/file-text.svg",
    Faktury: "/file-text.svg",
    Ustawienia: "/vector.svg",
};
